############################################################
# STEPS

# Steps to be done
steps: ["metathermo", "singlem", "metabolishmm", "metabolic", "microtrait", "multiqc"] 
  #steps: ["coverage"] #"microtrait", "genomad"


############################################################
# INPUT
# Directory where the workflow exists
work_dir: "/prj/DECODE/EA_metag_post_analysis"

# Directory where the data files are
data_dir: "/prj/DECODE/EA_metag_post_analysis/data" # USER_INPUT

# Directory for the results
results_dir: "/prj/DECODE/ea_analysis/results_20240915" # USER_INPUT

# Directory where the conda environments are
env_dir: "/prj/DECODE/EA_metag_post_analysis/envs"

# Directory with scripts
src_dir: "/prj/DECODE/EA_metag_post_analysis/scripts"

# Samples (if a relative path, relative to this repo)
samples: "config/450_samples.tsv" # USER_INPUT

# Directory for databases
db_dir: "/prj/DECODE/ea_analysis/database"

############################################################
# TOOLS 
# SINGLEM
# # https://wwood.github.io/singlem/Installation
singlem:
  threads: 18
  db: "S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb"  # export SINGLEM_METAPACKAGE_PATH='/ei/.project-scratch/0/0e51ef86-0156-4e79-ad12-c5411c0a5496/databases/singlem/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb'

prodigal:
  threads: 12

genomad:
  splits: 12
  threads: 24

checkm:
  threads: 64
  extension: "fa"
  git_path: "https://github.com/chklovski/CheckM2"

drep:
  threads: 64
  comp: 70
  cont: 16

gtdbtk:
  threads: 64
  path: "/hdd0/susbus/databases/gtdbtk/release214"

mapping:
  threads: 36

metabolic:
  path: "/prj/DECODE/ea_biofilm_results/metabolic/METABOLIC"

multiqc:
  threads: 64
